# Generated by Django 2.2.7 on 2019-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('cpercent', models.IntegerField(blank=True, null=True)),
                ('cid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
